dist: trusty
language: java
jdk: oraclejdk8
sudo: required

# set android sdk environment variable
env:
  - ANDROID_HOME=$HOME/android-sdk-linux

before_install:
   - nvm install 0.10
   - pip install coveralls
   - sudo apt-get install lib32stdc++6 lib32z1

install:
  # Disable Travis CI's built-in NVM installation
  - mv ~/.nvm ~/.travis-nvm-disabled
  - ./setup_server.sh
  - ./installSDK.sh

# Emulator Management: Create
before_script:
  - export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
  - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a

# run gradle lint and gradle build without using using tests for now (assemble)
# on debug build only
script:
#uncomment the code below when tests are not flaky
#  - ./getIp.sh
#  - ./run.sh
  - ./gradlew lintDebug
  - ./gradlew assembleDebug
addons:
  postgresql: "9.3"
  apt:
    packages:
      - iproute2