language: android
jdk: oraclejdk8
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
android:
  components:
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-25.0.2

    # The SDK version used to compile your project
    - android-25

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # uncomment when we enable espresso tests
    # - sys-img-armeabi-v7a-android-21

  licenses:
   - 'android-sdk-license-.+'

# uncomment the following lines to use emulator while runnning espresso tests
# Emulator Management: Create, Start and Wait
#before_script:
#  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
#  - emulator -avd test -no-skin -no-audio -no-window &
#  - android-wait-for-emulator
#  - adb shell input keyevent 82 &

# run gradle lint and
# gradle build without using using tests for now (assemble) on debug build only
script:
  - ./gradlew lintDebug
  - ./gradlew assembleDebug
notifications:
  webhooks:
    urls:
      - https://zulip.org/zulipbot/travis
    on_success: always
    on_failure: always
